version: '3.5'

services:
  web:
    build:
      context: .
    container_name: node
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./:/usr/app/src
    networks:
      - backend
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mongo:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
    networks:
      - backend

volumes:
  mongo:

networks:
  backend:
    name: node-backend
