version: '3.5'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./config/docker/node.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  web:
    build: .
    image: node-backend:latest
    volumes:
      - ./:/usr/app/src
    deploy:
      replicas: 3
    networks:
      - backend
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mongo:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PASSWORD}"
    networks:
      - backend

  redis:
    image: redis
    restart: always
    networks:
      - backend

volumes:
  mongo:

networks:
  backend:
    name: node-backend
